language: php
cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - mysql

php:
  - 7.2
  - 7.3

env:
  - SYMFONY_REQUIRE="3.4.*"
  - SYMFONY_REQUIRE="4.4.*"
  - SYMFONY_REQUIRE="5.0.*"
  - PHPUNIT_VERSION="8.*"

matrix:
  include:
    - php: 7.3
      env:
        - TEST_COVERAGE=true
    - php: 7.1
      env:
        - PHPUNIT_VERSION="7.*"
        - SYMFONY_REQUIRE="3.4.*"
    - php: 7.4
      env:
        - SYMFONY_REQUIRE="5.1.*"
        - PHPUNIT_VERSION="9.*"

before_install:
    - phpenv config-rm xdebug.ini || echo "xDebug not disabled"
    - composer global require --no-progress --no-scripts --no-plugins symfony/flex

install:
  - rm -rf composer.lock vendor/*
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - composer require phpunit/phpunit:${PHPUNIT_VERSION:-"8.*"} --update-with-all-dependencies

script:
  - cp tests/Functional/parameters.yml.dist tests/Functional/parameters.yml
  - rm -rf tests/Functional/cache
  - make phpstan php_cs_fixer_check
  - |
    if [[ ${TEST_COVERAGE} ]]; then phpdbg -qrr vendor/bin/phpunit -c tests/ --coverage-clover ./build/logs/clover.xml;
    elif [[ ${PHPUNIT_VERSION} == "7.*" ]]; then vendor/bin/phpunit -c tests/phpunit7.xml tests/;
    else vendor/bin/phpunit -c tests/ tests/;
    fi

after_success:
  - if [[ ${TEST_COVERAGE} ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ ${TEST_COVERAGE} ]]; then php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml; fi
